### ISSUE TITLE
Error email verification

### ISSUE THREAD

**Issue by sepol-sys** [zulfahmidev/capstone_api#6]
![image](https://github.com/zulfahmidev/capstone_api/assets/109580466/68294115-e797-4985-94df-1feb6e1e509a)

sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when one or none was required

**Comment by zulfahmidev** [comment]
Thank you for the issue, i have to repair this bug. The problem because secret key is always update after start service then can't decrypt token to get email who registered, so that can't find the email thats return all emails from db.
