### ISSUE TITLE
flask upgrade

### ISSUE THREAD

**Issue by sepol-sys** [zulfahmidev/capstone_api#7]
jalan kan perintah flask upgrade, ketika perintah python app.py

**Comment by zulfahmidev** [comment]
saya tidak tidak yakin itu bisa dijalankan melalui program, saya rasa lebih baik saat anda menjalankan perintah `python app.py` tambahkan perintah `flask upgrade` di awal, sehingga menjadi perintah `flask upgrade & python app.py`.

**Comment by sepol-sys** [comment]
tambahkan scrip berikut pada file app.py

import os
from app import app, db, mgr

if __name__ == '__main__' :
    with app.app_context():
        # Migrate the database
        os.system('flask db init')
        os.system('flask db migrate')
        os.system('flask db upgrade')

    app.run(debug=os.getenv('APP_DEBUG'), host='0.0.0.0')

**Comment by zulfahmidev** [comment]
oke, siap. terimakasih sudah membantu

**Comment by sepol-sys** [comment]
fix
