### ISSUE TITLE
wrong response

### ISSUE THREAD

**Issue by sepol-sys** [zulfahmidev/capstone_api#8]
![image](https://github.com/zulfahmidev/capstone_api/assets/109580466/52eb28b2-d64c-4b89-b07f-7f1f715de582)

**Comment by sepol-sys** [comment]
![image](https://github.com/zulfahmidev/capstone_api/assets/109580466/8a135782-53a1-493a-8bc2-d440fb798ff0)

**Comment by zulfahmidev** [comment]
maybe your login token has been expired or your secret key or jwt key has changed.
